{% set version = "2.20.0" %}
{% set name = "librealsense2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://github.com/IntelRealSense/librealsense/archive/v{{ version }}.tar.gz
  sha256: 01824767d8fb933f9487e97d50a941594abd18b6140c5c864bbf0db22dc62115

build:
  skip: true  # [win or osx]
  number: 0

about:
  home: https://www.intelrealsense.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  
  summary: |
    Intel® RealSense™ SDK 2.0 is a cross-platform library for Intel® RealSense™ 
    depth cameras (D400 series and the SR300) and the T265 tracking camera.
  description: |
    The SDK allows depth and color streaming, and provides intrinsic and 
    extrinsic calibration information. The library also offers synthetic 
    streams (pointcloud, depth aligned to color and vise-versa), and a built-in
    support for record and playback of streaming sessions. 
    
    Developer kits containing the necessary hardware to use this library are 
    available for purchase at store.intelrealsense.com. Information about the 
    Intel® RealSense™ technology at www.intelrealsense.com.
  doc_url: https://github.com/IntelRealSense/librealsense/blob/master/readme.md
  dev_url: https://github.com/IntelRealSense/librealsense

extra:
  recipe-maintainers:
    - mjscosta

